/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiersRouteImport } from './routes/tiers'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerUuidRouteImport } from './routes/player.$uuid'

const TiersRoute = TiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerUuidRoute = PlayerUuidRouteImport.update({
  id: '/player/$uuid',
  path: '/player/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/tiers': typeof TiersRoute
  '/player/$uuid': typeof PlayerUuidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/tiers': typeof TiersRoute
  '/player/$uuid': typeof PlayerUuidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/leaderboard': typeof LeaderboardRoute
  '/tiers': typeof TiersRoute
  '/player/$uuid': typeof PlayerUuidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/leaderboard' | '/tiers' | '/player/$uuid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/leaderboard' | '/tiers' | '/player/$uuid'
  id: '__root__' | '/' | '/admin' | '/leaderboard' | '/tiers' | '/player/$uuid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LeaderboardRoute: typeof LeaderboardRoute
  TiersRoute: typeof TiersRoute
  PlayerUuidRoute: typeof PlayerUuidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tiers': {
      id: '/tiers'
      path: '/tiers'
      fullPath: '/tiers'
      preLoaderRoute: typeof TiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$uuid': {
      id: '/player/$uuid'
      path: '/player/$uuid'
      fullPath: '/player/$uuid'
      preLoaderRoute: typeof PlayerUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LeaderboardRoute: LeaderboardRoute,
  TiersRoute: TiersRoute,
  PlayerUuidRoute: PlayerUuidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
